// Mock goat screams dataset for early development per order.md

/**
 * Minimal media object helper to avoid undefineds
 */
const mediaAudio = id => ({
  mp3: {
    high: `https://example.com/audio/${id}_high.mp3`,
    medium: `https://example.com/audio/${id}_medium.mp3`,
    low: `https://example.com/audio/${id}_low.mp3`,
  },
  wav: {
    high: `https://example.com/audio/${id}_high.wav`,
    medium: `https://example.com/audio/${id}_medium.wav`,
    low: `https://example.com/audio/${id}_low.wav`,
  },
  ogg: {
    high: `https://example.com/audio/${id}_high.ogg`,
    medium: `https://example.com/audio/${id}_medium.ogg`,
    low: `https://example.com/audio/${id}_low.ogg`,
  },
});

const now = (y, m = 1, d = 1) => new Date(Date.UTC(y, m - 1, d)).toISOString();

const screams = [
  {
    id: 'goat-001',
    title: 'Classic Yelling Goat',
    source_type: 'viral_video',
    year: 2008,
    date_added: now(2020, 1, 1),
    timestamp: '00:00:03',
    source: {
      title: 'Original Viral Goat',
      platform: 'YouTube',
      url: 'https://youtube.com/watch?v=original-goat',
      creator: 'GoatFan01',
    },
    goat: { breed: 'Nubian', age: 'Adult', color: 'brown' },
    audio: { duration: 2.3, intensity: 10, category: 'short_burst' },
    analysis: {
      descriptor: null,
      vibe: null,
      tags: [],
      primary_note: null,
      tones_in_order: [],
    },
    media: { audio: mediaAudio('goat-001') },
    tags: ['funny', 'viral', 'classic'],
    meme_status: 'legendary',
    remix_count: 42,
    context: 'The original viral goat that started it all',
    stats: { api_calls: 0, downloads: 0, favorites: 0 },
  },
  {
    id: 'goat-002',
    title: 'Taylor Swift Goat Remix',
    source_type: 'viral_video',
    year: 2013,
    date_added: now(2020, 1, 2),
    timestamp: '00:00:45',
    source: {
      title: 'I Knew You Were Trouble (Goat)',
      platform: 'YouTube',
      url: 'https://youtube.com/watch?v=taylor-goat',
      creator: 'RemixMaster',
    },
    goat: { breed: 'Alpine', age: 'Adult', color: 'white' },
    audio: { duration: 1.8, intensity: 8, category: 'short_burst' },
    analysis: {
      descriptor: null,
      vibe: null,
      tags: [],
      primary_note: null,
      tones_in_order: [],
    },
    media: { audio: mediaAudio('goat-002') },
    tags: ['meme', 'music', 'viral'],
    meme_status: 'viral',
    remix_count: 120,
    context: 'Goat scream synced with chorus',
    stats: { api_calls: 0, downloads: 0, favorites: 0 },
  },
  {
    id: 'goat-003',
    title: 'Farm Feeding Frenzy',
    source_type: 'farm_recording',
    year: 2019,
    date_added: now(2020, 1, 3),
    source: { title: 'Tennessee Farm', platform: 'Field', farm_location: 'Tennessee' },
    goat: { breed: 'Boer', age: 'Young', color: 'white/brown' },
    audio: { duration: 3.1, intensity: 7, category: 'multiple' },
    analysis: {
      descriptor: null,
      vibe: null,
      tags: [],
      primary_note: null,
      tones_in_order: [],
    },
    media: { audio: mediaAudio('goat-003') },
    tags: ['farm', 'multiple', 'ambient'],
    meme_status: 'emerging',
    remix_count: 2,
    context: 'Feeding time chaos',
    stats: { api_calls: 0, downloads: 0, favorites: 0 },
  },
  {
    id: 'goat-004',
    title: 'Movie Background Baa',
    source_type: 'movie',
    year: 2009,
    date_added: now(2020, 1, 4),
    timestamp: '00:45:23',
    source: { title: 'The Men Who Stare at Goats', platform: 'Blu-ray', director: 'Grant Heslov' },
    goat: { breed: 'Unknown', age: 'Adult', color: 'black' },
    audio: { duration: 2.0, intensity: 5, category: 'short_burst' },
    analysis: {
      descriptor: null,
      vibe: null,
      tags: [],
      primary_note: null,
      tones_in_order: [],
    },
    media: { audio: mediaAudio('goat-004') },
    tags: ['movie', 'background'],
    meme_status: 'classic',
    remix_count: 1,
    context: 'Background farm scene',
    stats: { api_calls: 0, downloads: 0, favorites: 0 },
  },
  {
    id: 'goat-005',
    title: 'TikTok Screech',
    source_type: 'viral_video',
    year: 2021,
    date_added: now(2020, 1, 5),
    source: { title: 'Goat Scream TikTok', platform: 'TikTok', url: 'https://tiktok.com/@goat' },
    goat: { breed: 'Saanen', age: 'Adult', color: 'white' },
    audio: { duration: 1.2, intensity: 9, category: 'short_burst' },
    analysis: {
      descriptor: null,
      vibe: null,
      tags: [],
      primary_note: null,
      tones_in_order: [],
    },
    media: { audio: mediaAudio('goat-005') },
    tags: ['tiktok', 'short'],
    meme_status: 'emerging',
    remix_count: 12,
    context: 'Surprised by owner',
    stats: { api_calls: 0, downloads: 0, favorites: 0 },
  },
  {
    id: 'goat-006',
    title: 'Prolonged Howl',
    source_type: 'farm_recording',
    year: 2018,
    date_added: now(2020, 1, 6),
    source: { title: 'Iowa Pasture', platform: 'Field', farm_location: 'Iowa' },
    goat: { breed: 'Kiko', age: 'Adult', color: 'gray' },
    audio: { duration: 4.0, intensity: 6, category: 'prolonged' },
    analysis: {
      descriptor: null,
      vibe: null,
      tags: [],
      primary_note: null,
      tones_in_order: [],
    },
    media: { audio: mediaAudio('goat-006') },
    tags: ['prolonged', 'ambient'],
    meme_status: 'underground',
    remix_count: 0,
    context: 'Long-distance call',
    stats: { api_calls: 0, downloads: 0, favorites: 0 },
  },
  {
    id: 'goat-007',
    title: 'Melodic Bleat',
    source_type: 'farm_recording',
    year: 2017,
    date_added: now(2020, 1, 7),
    source: { title: 'Oregon Hills', platform: 'Field', farm_location: 'Oregon' },
    goat: { breed: 'LaMancha', age: 'Adult', color: 'tan' },
    audio: { duration: 2.7, intensity: 4, category: 'melodic' },
    analysis: {
      descriptor: null,
      vibe: null,
      tags: [],
      primary_note: null,
      tones_in_order: [],
    },
    media: { audio: mediaAudio('goat-007') },
    tags: ['melodic', 'calm'],
    meme_status: 'underground',
    remix_count: 0,
    context: 'Gentle melodic bleat',
    stats: { api_calls: 0, downloads: 0, favorites: 0 },
  },
  {
    id: 'goat-008',
    title: 'Super Bowl Ad Goat',
    source_type: 'viral_video',
    year: 2013,
    date_added: now(2020, 1, 8),
    source: {
      title: 'Doritos Super Bowl',
      platform: 'YouTube',
      url: 'https://youtube.com/watch?v=doritos-goat',
    },
    goat: { breed: 'Boer', age: 'Adult', color: 'brown' },
    audio: { duration: 1.6, intensity: 7, category: 'short_burst' },
    analysis: {
      descriptor: null,
      vibe: null,
      tags: [],
      primary_note: null,
      tones_in_order: [],
    },
    media: { audio: mediaAudio('goat-008') },
    tags: ['ad', 'superbowl', 'funny'],
    meme_status: 'classic',
    remix_count: 6,
    context: 'Commercial chaos',
    stats: { api_calls: 0, downloads: 0, favorites: 0 },
  },
  {
    id: 'goat-009',
    title: 'Multiple Rapid Calls',
    source_type: 'farm_recording',
    year: 2020,
    date_added: now(2020, 1, 9),
    source: { title: 'Wisconsin Barn', platform: 'Field', farm_location: 'Wisconsin' },
    goat: { breed: 'Nigerian Dwarf', age: 'Young', color: 'black/white' },
    audio: { duration: 2.2, intensity: 6, category: 'multiple' },
    analysis: {
      descriptor: null,
      vibe: null,
      tags: [],
      primary_note: null,
      tones_in_order: [],
    },
    media: { audio: mediaAudio('goat-009') },
    tags: ['multiple', 'farm'],
    meme_status: 'emerging',
    remix_count: 1,
    context: 'Feeding call pattern',
    stats: { api_calls: 0, downloads: 0, favorites: 0 },
  },
  {
    id: 'goat-010',
    title: 'Horror-Movie Quality Scream',
    source_type: 'viral_video',
    year: 2015,
    date_added: now(2020, 1, 10),
    source: {
      title: 'Creepy Goat',
      platform: 'YouTube',
      url: 'https://youtube.com/watch?v=creepy-goat',
    },
    goat: { breed: 'Unknown', age: 'Adult', color: 'black' },
    audio: { duration: 2.9, intensity: 9, category: 'prolonged' },
    analysis: {
      descriptor: null,
      vibe: null,
      tags: [],
      primary_note: null,
      tones_in_order: [],
    },
    media: { audio: mediaAudio('goat-010') },
    tags: ['horror', 'loud'],
    meme_status: 'classic',
    remix_count: 3,
    context: 'Horror-movie quality scream',
    stats: { api_calls: 0, downloads: 0, favorites: 0 },
  },
];

module.exports = screams;
